// <auto-generated />
namespace ShisheVere.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changecolblerestousername : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changecolblerestousername));
        
        string IMigrationMetadata.Id
        {
            get { return "201809120917584_change col bleres to username"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
