// <auto-generated />
namespace ShisheVere.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deleteconstrainrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteconstrainrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201809200853085_delete constrain required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
